### ISSUE TITLE
missing base64.h file

### ISSUE THREAD

**Issue by mthenault** [solar-storm-studios/TMXParser#1]
Hello, sorry if this issue is maybe trivial but the TMXParser.cpp file includes a base64.h file. 
I'm compiling with mingw and i don't have this file. 
How to get this file ? 

Many thanks in advance

**Comment by desrik** [comment]
Find where base64.h is included and remove it. I failed at getting the
base64 decoding implemented. Must have forgotten to remove the include line.

**Comment by mthenault** [comment]
Ok thanks. 
Now the tmx.load() function segfaults.
I used the example code and the desert.tmx default file : 

``` c++
TMX::Parser tmx;
 tmx.load( "desert.tmx" );
```

The debugger tells me that the issue comes from line 52 of TMXParser.cpp :

``` c++
 if( root_node->first_attribute( "backgroundcolor" )->value() != 0 ) {
```

I opened the .tmx file and there is base64 encoding inside, how can this work with your code without the base64 decoding implementation ? 

Is that supposed to work ?

**Comment by desrik** [comment]
Here are the files I used when creating and testing TMXParser: https://drive.google.com/folderview?id=0ByCLmkul_nrJQV9oNlRiOFNWX1k&usp=sharing

No, base64 is not supported. CSV only.
